### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by mofogasy** [SchweizerischeBundesbahnen/scion-workbench#72]
## Is your feature request related to a problem? Please describe.
When a lot of views are open at a given moment, especially if they are arranged in different sashes, a single view can get exceedingly small. Although the activity part can be hidden by double-clicking on the view tab, the view doesn't grow much if the grid is big enough.

## Describe the solution you'd like
A full screen mode where a single view takes the whole available screen space.

## Describe alternatives you've considered
None

#### With activity part
![image](https://user-images.githubusercontent.com/30831552/49995066-6c75da00-ff8b-11e8-894c-95afe116a0f6.png)

#### Without activity part
![image](https://user-images.githubusercontent.com/30831552/49994969-333d6a00-ff8b-11e8-9e93-a10738b3a7bc.png)

**Comment by danielwiehl** [comment]
Thank you for creating this issue and PR.

I think it will require some triage, especially because we plan to make the workbench responsive so that it is consistent with the concept in our mind.

Currently, we are in the process of completing the initial development of the Workbench Application Platform. To stay focused, we'd like to defer this issue until Q2 this year.
